### ISSUE TITLE
Document definition file pattern for ambient modules which export single function.

### ISSUE THREAD

**Issue by traviskaufman** [Microsoft/TypeScript-Handbook#141]
This is a common pattern for node modules, and it wasn't immediately apparent to me from the "Single Complex Object in External Modules" example.

Example: https://www.npmjs.com/package/stream-to-promise

```typescript
declare module 'stream-to-promise' {
  import {Promise} from 'es6-promise';
  export default function streamToPromise<T>(stream: NodeJS.ReadableStream): Promise<T>;
}
```

**Comment by DanielRosenwasser** [comment]
[You mean like this?](https://github.com/Microsoft/TypeScript-Handbook/blob/008c280f886daad2bcf16ad0fca05ee6258deb14/pages/Writing%20Definition%20Files.md#global--external-agnostic-libraries)

Yeah, what a horrible title. If you'd be willing to make it a little clearer, we'd accept a PR. Otherwise, we'll take care of it.

**Comment by traviskaufman** [comment]
Yeah similar to that, except that the object required would be a function, e.g.

```javascript
// An amazing node module that says hello.
module.exports = function sayHello(name) { 
  console.log('Hello, %s!', name); 
};
```

I'd be happy to submit a PR. What do you think of the title "Function exports" (inspired by [this S.O. question](http://stackoverflow.com/questions/5872457/node-js-export-function-without-object-wrapper))?

```typescript
import sayHello = require('say-hello');
sayHello();
```

```
declare module 'say-hello' {
  function sayHello(name: string): void;
  export = sayHello;
}
```
