### ISSUE TITLE
How to declare a statement in d.ts that has both an instance method and an instance attribute and has same name

### ISSUE THREAD

**Issue by freezestudio** [Microsoft/TypeScript-Handbook#233]
e.g.

javascript class: Test

Instance Methods : var number=test.size();
Instance Variables : size     Type: Number

in .d.ts  How to declare it?

thanks!

or see:http://www.nodegit.org/api/diff_file/#size

**Comment by DanielRosenwasser** [comment]
I think the documentation is mistaken. Each of those appears to be a *function* that returns those types. Can you try the API out and confirm? Perhaps @jvilk would be able to answer.

Additionally, make sure that you use *primitives* in place of their capitalized interface types. (i.e. use `number` instead of `Number`!).

Lastly, it's no big deal, but in the future these sorts of questions are typically better asked on StackOverflow. 😃

**Comment by jvilk** [comment]
I have been summoned! @freezestudio, [I am working with nodegit to generate TypeScript typings from its documentation](https://github.com/nodegit/nodegit.github.com/pull/38). @DanielRosenwasser is correct: the documentation is *incorrect*. All of those "Instance Variables" are actually *functions*.

`DiffFile` [looks like this in the typings](https://gist.github.com/jvilk/04b83573f60f29c9ce7c#file-nodegit-d-ts-L1262).

Hope that helps!

**Comment by freezestudio** [comment]
Thank you so much for your help.
