### ISSUE TITLE
Suggestion for update examples for Interface page

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript-Handbook#366]
_This is an [issue ](https://github.com/Microsoft/TypeScript/issues/10301)moved from TypeScript Repo_

Handbook link: https://www.typescriptlang.org/docs/handbook/interfaces.html

In the last topic, Interfaces Extending Classes, the extends in the example code differ from what the explanation below tells.

Here is my suggestion for a new code example:

``` ts
class Control {
    private state: any;
}

interface SelectableControl extends Control {
    select(): void;
}

class Button extends Control implements SelectableControl {
    select() { }
}

class TextBox extends Control implements SelectableControl {
    select() { }
}

class Image extends Control {
}

class Location extends Control {
    select() { }
}
```

**Comment by vovanmozg** [comment]
I also think that an example in the last topic looks incomplete.

I suggest my version of code https://github.com/Microsoft/TypeScript-Handbook/pull/637

```ts
class Control {
    private state: any;
}

interface SelectableControl extends Control {
    select(): void;
}

class Button extends Control implements SelectableControl {
    select() { }
}

class TextBox extends Control {
    
}

// Error: Property 'state' is missing in type 'Image'.
class Image implements SelectableControl {
    select() { }
}

class Location {
    
}
```

**Comment by vovanmozg** [comment]
@roblperry thank you for resuming the discussion. My suggestion was wrong. And the documentation example was wrong too.

I looked the changes history of interfaces.html. It seems that the original version was correct, but as a result of several edits, it began to be misleading (see https://github.com/Microsoft/TypeScript-Handbook/commit/25ae2209d442d095f7a2c51e8a54948b2ea26612#diff-0d122fa6d7fac71313bb600040376e83 by @sandersn ).

Suggestion:
1) to restore the code version of the creator

```ts
class Control {
    private state: any;
}

interface SelectableControl extends Control {
    select(): void;
}

class Button extends Control {
    select() { }
}

class TextBox extends Control {
    select() { }
}

class Image extends Control {
}

class Location {
    select() { }
}
```

2) add some text to the last paragraph:
`Image` has not `select()` method. `Location` has not private property `state`;

3) add additional example
```ts
let someVar: SelectableControl;

// Acceptable, because The TextBox is a descendant of the Control class
someVar = new TextBox();

// Type 'Image' is not assignable to type 'SelectableControl'.  Property 'select' is missing in type 'Image'.
someVar = new Image();
 
// Type 'Location' is not assignable to type 'SelectableControl'. Property 'state' is missing in type 'Location'.
someVar = new Location();
```

@sandersn could you help clarify the example and its description, because it seems that developers have difficulties with understanding this.

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript-Handbook/pull/698
