### ISSUE TITLE
Update React & Webpack for webpack 2

### ISSUE THREAD

**Issue by DanielFallon** [microsoft/TypeScript-Handbook#462]
Couple of things coming up:

- Webpack 2 is on the horizon (we're at RC 2)
- awesome-ts-loader is in pretty bad disrepair with the breaking changes from both webpack 2 and ts 2.1.*

Should we return this documentation to using ts-loader? for simple projects, the configuration is much easier, and the simplicity of that loader plugin means that its more likely to stay up to date long term.

Thoughts?
I'll start working on changes and a pull request sometime this weekend

DJF

**Comment by mhegazy** [comment]
@DanielRosenwasser thoughts?

**Comment by DanielRosenwasser** [comment]
@TheLarkInn thoughts?

In my opinion, if ts-loader is Webpack 2-ready, ts-loader it is.

**Comment by chicoxyzzy** [comment]
It should be mentioned that code splitting with dynamic imports is currently unavailable https://github.com/Microsoft/TypeScript/issues/12364

**Comment by TheElf** [comment]
just to clarify @chicoxyzzy, that's a deficiency of the typescript syntax right now.

As a result, at-loader would be unable to handle this correct?

also a large portion of why I wanted to move back to ts-loader was because it just appears to be better maintained. 
 - CI build for awesome-typescript-loader/master has been broken for about 2 months
 - The unit tests don't appear to reflect the currently documented API
 - and there aren't a lot of contributors. ts-loader, in contrast, appears to be a fairly thin shim and has multiple significant contributors.

**Comment by chicoxyzzy** [comment]
I understand, it was just a side note. Because it should be clear that not all features of Webpack 2 are available with current version of TypeScript to prevent future misunderstanding. So if documentation will be updated for Webpack 2 it seems legit to add note about dynamic imports

**Comment by mbertram** [comment]
@orta I think this can be closed. The tutorial was updated for a current webpack version (#765).

**Comment by orta** [comment]
Great, thanks @mbertram
